development:
  adapter: postgresql
  encoding: unicode
  database: josched_development
  pool: 5
  username: eman
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: josched_test
  pool: 5
  username: eman
  password:
  min_messages: error
